--- # Start - Spring
spring:
  datasource:
    url: jdbc:h2:mem:cifras;MODE=MySQL;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: h2user
    password: h2pass
    driverClassName: org.h2.Driver

  flyway:
    locations: classpath:db/migration,db/specific/h2

  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
... #End - Spring