
--- #Start - Server
server:
  port: 8090
... #End - Server

--- # Start - Spring
spring:
  #main:
  #  banner-mode: log

  output:
    ansi:
      enabled: DETECT

  datasource:
    url: jdbc:postgresql://localhost:5432/cifras
    username: postgres
    password: pgroot123
    driverClassName: org.postgresql.Driver

  flyway:
    baseline-on-migrate: true
    fail-on-missing-locations: false
    locations: classpath:/db/migration

  jpa:
    #open-in-view: false
    show-sql: false
    generate-ddl: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql : true
... #End - Spring

--- #Start - Logging with Logback's Library
logging:
  file:
    name: logs/CifreSuasMusicas.log

  pattern:
    console: "[%d] [%-5level] [%-40.40logger{39}] : %msg%n"
    file: "[%d] [%-5level] [%-40.40logger{39}] : %msg%n"

  logback:
    rollingpolicy:
      file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz"
      max-file-size: 15MB
      max-history: 7
      total-size-cap: 210MB

  level:
    root: warn
    com.myprojects.cadclients: info
    org.springframework: error
    org.springframework.boot.SpringApplication: info
    org.hibernate: error
    #org.hibernate.SQL: debug
    #org.hibernate.type.descriptor.sql: trace
    org.apache.tomcat: error
... #End - Logging