--- #Start - Server
server:
  port: 8090
... #End - Server

--- # Start - Spring
spring:
  #main:
    #banner-mode: log

  #datasource:
  #  url: jdbc:postgresql://localhost:5432/cifras
  #  username: postgres
  #  password: pgroot123
  #  driverClassName: org.postgresql.Driver

  datasource:
    url: jdbc:h2:mem:cifras;MODE=MySQL;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: h2user
    password: h2pass
    driverClassName: org.h2.Driver

  h2:
    console:
      path: /h2-console
      enabled: true

  flyway:
    #locations: classpath:db/migration,db/specific/postgresql
    locations: classpath:db/migration,db/specific/h2

  jpa:
    #open-in-view: false
    show-sql: false
    generate-ddl: false
    #database: postgresql
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: true
... #End - Spring

--- #Start - Logging with Logback's Library
logging:
  file:
    name: logs/CifreSuasMusicas.log

  pattern:
    console: "[%d] [%-5level] [%-40.40logger{39}] : %msg%n"
    file: "[%d] [%-5level] [%-40.40logger{39}] : %msg%n"

  logback:
    rollingpolicy:
      file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz"
      max-file-size: 15MB
      max-history: 7
      total-size-cap: 210MB

  level:
    root: warn
    br.com.cifresuasmusicas: info
    org.springframework: error
    org.springframework.boot.SpringApplication: info
    org.flywaydb: info
    org.hibernate: error
    #org.hibernate.SQL: debug
    #org.hibernate.type.descriptor.sql: trace
    org.apache.tomcat: error
... #End - Logging