-- Creation of user table
CREATE TABLE IF NOT EXISTS TB_USER (
    user_id     INT GENERATED BY DEFAULT AS IDENTITY,
    username    VARCHAR(100) UNIQUE,
    password    VARCHAR(200),
    name        VARCHAR(255),
    cpf         VARCHAR(11) UNIQUE,
    phone       VARCHAR(15),
    sex         VARCHAR(1),
    email       VARCHAR(100),
    naturality  VARCHAR(40),
    nacionality VARCHAR(40),
    dt_birthday DATE NOT NULL,
    dt_create   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    dt_update   TIMESTAMP,
    PRIMARY KEY (user_id)
);

-- Creation of role table
CREATE TABLE IF NOT EXISTS TB_ROLE (
    role_id INT GENERATED BY DEFAULT AS IDENTITY,
    name    VARCHAR(40) UNIQUE,
    PRIMARY KEY (role_id)
);

-- Creation of relationship between user and role tables.
CREATE TABLE IF NOT EXISTS TB_USERS_ROLES (
    user_role_id INT GENERATED BY DEFAULT AS IDENTITY,
    user_id      INT NOT NULL,
    role_id      INT NOT NULL,
    PRIMARY KEY (user_role_id),
    UNIQUE (user_id, role_id),
    CONSTRAINT fk_users
        FOREIGN KEY (user_id)
            REFERENCES tb_user (user_id)
            ON DELETE CASCADE,
    CONSTRAINT fk_roles
        FOREIGN KEY (role_id)
            REFERENCES tb_role (role_id)
            ON DELETE CASCADE
);
